steps:
- name: 'gcr.io/cloud-builders/docker'
  secretEnv:
  - 'SERVICE_ACCOUNT_KEY'
  - 'SENTRY_KEY'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker build \
      -t "${_SERVICE_IMAGE_TAGGED_LATEST}" -t "${_SERVICE_IMAGE_TAGGED}" \
      -f Dockerfile.service \
      --build-arg "DUMP_DATE=${_DUMP_DATE}" \
      --build-arg "SERVICE_ACCOUNT_KEY=$$SERVICE_ACCOUNT_KEY" \
      --build-arg "SENTRY_AUTH_TOKEN=$$SENTRY_KEY" \
      .
- name: gcr.io/cloud-builders/docker
  args:
    - 'push'
    - '${_SERVICE_IMAGE_TAGGED_LATEST}'
- name: gcr.io/cloud-builders/docker
  args:
    - 'push'
    - '${_SERVICE_IMAGE_TAGGED}'
availableSecrets:
  secretManager:
  - versionName: projects/418523344453/secrets/wikiwalk-build-service-account-key/versions/1
    env: 'SERVICE_ACCOUNT_KEY'
  - versionName: projects/418523344453/secrets/wikiwalk-build-sentry-key/versions/1
    env: 'SENTRY_KEY'
options:
    dynamicSubstitutions: true
