# Build tool and server
# The generated image also has rsync and gcloud
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/supervillains/supervillains/wikiwalk-app:$COMMIT_SHA'
    - '-t'
    - 'us-central1-docker.pkg.dev/supervillains/supervillains/wikiwalk-app:latest'
    - '-f'
    - 'Dockerfile.app'
    - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'push'
    - 'us-central1-docker.pkg.dev/supervillains/supervillains/wikiwalk-app:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'push'
    - 'us-central1-docker.pkg.dev/supervillains/supervillains/wikiwalk-app:latest'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
    - 'auth'
    - 'list'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      find $(gcloud info --format='value(config.paths.global_config_dir)')
      echo "maybe credential files"
      find $(gcloud info --format='value(config.paths.global_config_dir)') -name '*.json'

  # Start Cloud Run Job to build the database (if necessary) and deploy the app to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
    - 'run'
    - 'jobs'
    - 'execute'
    - 'wikiwalk-build'
    - '--region=us-central1'
    - '--async'

timeout: 10800s
options:
  machineType: 'E2_HIGHCPU_8'
  automapSubstitutions: true
