steps:
  # Put data in GCS buckets
  - name: 'us-central1-docker.pkg.dev/supervillains/supervillains/wikiwalk-app:latest'
    entrypoint: ./wiki-dump-rc
    env:
      - 'TOOL_PATH=/tool'
  - name: 'us-central1-docker.pkg.dev/supervillains/supervillains/wikiwalk-app:latest'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        set -e
        /tool find-latest --date > /workspace/latest-build
  # Check to see if an image exists that has the latest build date
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
    entrypoint: /bin/bash
    args:
    - '-c'
    - |
      set -euo pipefail
      hash gcloud 2>/dev/null || {
        echo >&2 "I require gcloud but it's not installed.  Aborting."
        exit 1
      }

      export latest_dump=$(cat /workspace/latest-build)
      echo "Latest dump date: '$latest_dump'"
      service_image="us-central1-docker.pkg.dev/supervillains/supervillains/wikiwalk-service"
      service_image_tagged="$service_image:$COMMIT_SHA-$latest_dump"
      echo "Checking for image: '$service_image_tagged'"
      gcloud artifacts docker images describe "$service_image_tagged" || {
        echo "Image not found, building..."
        service_image_tagged_latest="$service_image:latest"
        gcloud builds submit . \
          --config cloudbuild-service.yaml \
          --substitutions _SERVICE_IMAGE_TAGGED="$service_image_tagged",_SERVICE_IMAGE_TAGGED_LATEST="$service_image_tagged_latest",_DUMP_DATE="$latest_dump" \
          --region us-central1 \
          --timeout=10800s
        echo "Cloud build submitted"
      }
timeout: 10800s
options:
  machineType: 'E2_HIGHCPU_8'
  automapSubstitutions: true
