# Build the data to bake into the image
FROM us-central1-docker.pkg.dev/supervillains/supervillains/wikiwalk-build AS data-builder
RUN mkdir /data
RUN rclone cp --include="*$(cat /workspace/dump-date)*.sql.gz" :gcs:wikiwalk /data/dumps/
RUN find /data
RUN /tool build --dump-date $(cat /workspace/dump-date)
