FROM us-central1-docker.pkg.dev/supervillains/supervillains/wikiwalk-app
WORKDIR /app
ARG DUMP_DATE
# RUN /tool fetch --dump-date $DUMP_DATE
COPY data /data
RUN find /data && /tool build --dump-date $DUMP_DATE  && rm -rf /data/dumps
CMD [ "/server" ]
