FROM us-central1-docker.pkg.dev/supervillains/supervillains/wikiwalk-app
WORKDIR /app
ARG DUMP_DATE
ARG SERVICE_ACCOUNT_KEY
ENV DUMP_DATE=${DUMP_DATE}
ENV SERVICE_ACCOUNT_KEY=${SERVICE_ACCOUNT_KEY}
RUN mkdir -p /data/${DUMP_DATE} && \
  (echo "${SERVICE_ACCOUNT_KEY}" | gcloud auth activate-service-account --key-file=-) && \
  gcloud storage cp --recursive "gs://wikiwalk-dumps/${DUMP_DATE}/*" "/data/${DUMP_DATE}" && \
  ln -s /data/${DUMP_DATE} /data/current
CMD [ "/server" ]
