#!/bin/bash
set -euo pipefail

# Copy the latest dump from the Wikimedia Foundation to Google Cloud Storage.
hash rclone 2>/dev/null || {
  echo >&2 "I require rclone but it's not installed.  Aborting."
  exit 1
}

tool="${TOOL_PATH:-/tool}"
dump_source_host="https://dumps.wikimedia.org/"

while read -r line
do
  rclone copy \
    --multi-thread-streams 3 \
    --size-only \
    --http-url "$dump_source_host" \
    --log-level INFO \
    ":http:$line" ":gcs:wikiwalk/dumps"
done < <("$tool" find-latest --urls --relative)
