#!/bin/bash
set -euo pipefail
status="error"
[[ $SERVICE_RESULT = success ]] && [[ $EXIT_CODE = exited ]] && status="complete"
/usr/bin/curl "https://o4506004333199360.ingest.sentry.io/api/4506004334510080/cron/build-graph/2377de2b8f109351d1d4d349e0f152e0/?status=${status}"
