#!/bin/bash
set -euo pipefail
CERT_PATH="/var/wikiwalk/certs"
WEBROOT_PATH="/var/wikiwalk/webroot"
echo "fetching certificates"
if [[ -d "$CERT_PATH" ]]
then
    echo "$CERT_PATH exists, using webroot"
    /usr/local/bin/lego \
        --accept-tos \
        --path "$CERT_PATH" \
        --email="LiamBowen@gmail.com" \
        --domains="wikiwalk.app" \
        --key-type ec256 \
        --http \
        --http.webroot "$WEBROOT_PATH" \
        run
else
    echo "$CERT_PATH does not exist, using standalone"
    /usr/local/bin/lego \
        --accept-tos \
        --path "$CERT_PATH" \
        --email="LiamBowen@gmail.com" \
        --domains="wikiwalk.app" \
        --key-type ec256 \
        --http \
        run
fi
