//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub use super::link_target::Entity as LinkTarget;
pub use super::path::Entity as Path;
pub use super::search::Entity as Search;
pub use super::vertex::Entity as Vertex;
