name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --verbose
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: List files
        run: ls -l target/release && which scp
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy tool
        run: scp -vv target/release/tool ${{ secrets.DEPLOY_SERVER }}:/var/wikiwalk/bin/wikiwalk-tool
      - name: Deploy server
        run: scp -vv target/release/server ${{ secrets.DEPLOY_SERVER }}:/var/wikiwalk/bin/wikiwalk-server
